apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: python:3.9
        ports:
        - containerPort: 80
        lifecycle:
          postStart:
            exec:
              command: ["python3", "-m", "http.server"]