apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-postgres
  template:
    metadata:
      labels:
        app: test-postgres
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1-ubuntu-seoul
      containers:
        - name: test-postgres
          image: postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: test-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: test-postgredb
              subPath: postgres
      volumes:
        - name: test-postgredb
          persistentVolumeClaim:
            claimName: file-share-pvc-0