apiVersion: v1
kind: Service
metadata:
  name: cockpit-service
spec:
  type: ExternalName
  externalName: 10.8.0.1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cockpit-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - YOUR.HOST.NAME
    secretName: master-certmanager-cockpit-nip-io
  rules:
  - host: YOUR.HOST.NAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cockpit-service
            port:
              number: 9090